//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseManagement.Web
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.WebControls.Panel pnlSummary;
        protected global::System.Web.UI.WebControls.Label lblTotalTransactions;
        protected global::System.Web.UI.WebControls.Label lblTotalExpense;
        protected global::System.Web.UI.WebControls.Label lblTotalBudgets;
        protected global::System.Web.UI.WebControls.Label lblTotalBudgetAmount;
        protected global::System.Web.UI.WebControls.Label lblRemainingBudget;
        protected global::System.Web.UI.WebControls.Label lblNoTransactions;
        protected global::System.Web.UI.WebControls.GridView gvRecentTransactions;
    }
}
